/// <reference types="nativewind/types" />

import "react-native";

declare module "react-native" {
    interface ViewProps {
        className?: string;
    }
    interface TextProps {
        className?: string;
    }
    interface ImageProps {
        className?: string;
    }
    interface TouchableOpacityProps {
        className?: string;
    }
    interface FlatListProps<ItemT> {
        className?: string;
    }
}

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.